CHI-1629 process contact job ecs task (#285)
* feat: separate job processor from api server

* chore: job processor deployment

* fix: spacing

* fix: fail to start docker contianer on migration failure

* fix: correct container name for ecs task

* fix: messages not being removed from complete queue

* fix: cleanup

* chore: fix test to match new behavior

diff --git a/hrm-service/docker-entrypoint b/hrm-service/docker-entrypoint
--- a/hrm-service/docker-entrypoint
+++ b/hrm-service/docker-entrypoint
@@ -1,11 +1,22 @@
 #!/usr/bin/env sh
 
-# Execute hrm-service migrations
-node ./db-migrate
+if [ -n "$HRM_RUN_MIGRATIONS" ]; then
+  # Execute hrm-service migrations
+  node ./db-migrate
+  if [ $? -ne 0 ]; then
+    echo "Failed to run hrm-service migrations"
+    exit 1
+  fi
 
-# Execute resources-service migrations (move once the service lives in it's own container)
-cd ./resources-service
-node ./db-migrate
-cd ..
+  # Execute resources-service migrations (move once the service lives in it's own container)
+  cd ./resources-service
+  node ./db-migrate
+  if [ $? -ne 0 ]; then
+    echo "Failed to run resource-service migrations"
+    exit 1
+  fi
+
+  cd ..
+fi
 
 exec "$@"
