chore: deploy single lambda or deploy all lambdas

diff --git a/.github/workflows/hrm-lambdas-release.yml b/.github/workflows/hrm-lambdas-release.yml
--- a/.github/workflows/hrm-lambdas-release.yml
+++ b/.github/workflows/hrm-lambdas-release.yml
@@ -1,15 +1,36 @@
-name: '[Multi Region] Deploy HRM Lambdas'
+name: '[Multi Region] Deploy HRM Lambda'
 on:
   workflow_dispatch:
     inputs:
+      lambda_name:
+        description: 'hrm lambda name'
+        required: true
+        default: mock
+        type: choice
+        options:
+          - mock
+
       environment:
         description: HRM environment to deploy. E.G = development, staging, production (must match with the AWS environment value). Default value = development
         default: development
         required: true
-      region:
-        description: AWS region to deploy. E.G = us-east-1, eu-west-1 (must match with the AWS environment value). Default value = us-east-1
-        default: us-east-1
+        type: choice
+        options:
+          - development
+          - staging
+          - production
+
+      #TODO: I've mapped region to environment, below. See note there about multi-region setup
+      # region:
+      #   description: AWS region to deploy. E.G = us-east-1, eu-west-1 (must match with the AWS environment value). Default value = us-east-1
+      #   default: us-east-1
+      #   required: true
+
+      send-slack-message:
+        description: 'Specifies if should send a Slack message at the end of successful run. Defaults to true'
         required: true
+        type: boolean
+        default: true
 
   workflow_call:
     secrets:
@@ -20,27 +41,11 @@ on:
       # Should probably use the passed in region for everything but the GITHUB_ACTIONS_SLACK_BOT_TOKEN SSM parameter only exists in us-east-1
       AWS_DEFAULT_REGION:
         required: true
-    inputs:
-      environment:
-        description: HRM environment to deploy. E.G = development, staging, production (must match with the AWS environment value). Default value = development
-        type: string
-        default: development
-        required: true
-      region:
-        description: AWS region to deploy. E.G = us-east-1, eu-west-1 (must match with the AWS environment value). Default value = us-east-1
-        type: string
-        default: us-east-1
-        required: true
-      send-slack-message:
-        description: 'Specifies if should send a Slack message at the end of successful run. Defaults to true'
-        required: false
-        default: 'true'
-        type: string
 
 env:
-  AWS_DEFAULT_REGION: ${{ inputs.region }}
+  AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
   GITHUB_SHA: ${{ github.sha }}
-  DOCKER_IMAGE_BASE: 712893914485.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ inputs.environment }}-hrm-lambdas-
+  DOCKER_IMAGE_BASE: 712893914485.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ inputs.environment }}-hrm-lambdas-
 
 jobs:
   build-lambdas:
@@ -51,55 +56,31 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
 
-      # Allows us to use cache across jobs
-      - name: Lambdas Cache
-        uses: actions/cache@v3
-        env:
-          cache-name: cache-lambdas
-        with:
-          path: ~/lambdas
-          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
-
       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
           node-version: 14.x
 
-      - name: compile lambdas
+      # I still don't have full understanding of the region differences between env, but this is an option for skipping the region input
+      # if each env has multiple regions, this could be output and another matrix job could be produced to deploy to each region
+      - name: Set Env Based on Environment
+
+        run: |
+          case "${{ inputs.environment }}" in development) region="eu-west-1" ;; staging) region="eu-west-1" ;; production) region="eu-west-1" ;; *) echo "Invalid environment: ${{ inputs.environment }}" && exit 1 ;; esac &&
+          echo AWS_REGION=$region >> $GITHUB_ENV
+
+      - name: Compile Lambda
         run: |
           cd lambdas
           npm ci
-          npm run compile
-          cp * ~/lambdas
-
-  deploy-lambdas-docker:
-    name: Deploy Lambdas
-    runs-on: ubuntu-latest
-    needs: build-lambdas
-
-    # If we had a json based job configuration for use by terraform, we could also use it here
-    # to define the matrix of lambdas to deploy based on the env using this method:
-    # https://thekevinwang.com/2021/09/19/github-actions-dynamic-matrix/
-    strategy:
-      matrix:
-        lambdas: [mock]
-
-    steps:
-      # Restore cache from previous workflow
-      - name: Lambdas Cache
-        uses: actions/cache@v3
-        env:
-          cache-name: cache-lambdas
-        with:
-          path: ~/lambdas
-          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
+          npm run compile-${{ inputs.lambda_name }}
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ inputs.region }}
+          aws-region: ${{ env.AWS_REGION }}
 
       - name: Login to Amazon ECR
         id: login-ecr
@@ -109,14 +90,14 @@ jobs:
       - name: Build and Push Docker Image
         uses: docker/build-push-action@v2
         with:
-          context: ~/lambdas/src/${{ matrix.lambdas }}
+          context: ~/lambdas/src/${{ inputs.lambda_name }}
           file: ~/lambdas/Dockerfile
           push: true
-          tags: ${{ env.DOCKER_IMAGE_BASE }}${{ matrix.lambdas }}:latest, ${{ env.DOCKER_IMAGE_BASE }}/hrm-lambdas-${{ matrix.lambdas }}:${{ inputs.environment }}-${{ github.sha }}
+          tags: ${{ env.DOCKER_IMAGE_BASE }}${{ inputs.lambda_name }}:latest, ${{ env.DOCKER_IMAGE_BASE }}/hrm-lambdas-${{ matrix.lambdas }}:${{ inputs.environment }}
 
       - name: Update Lambda and Publish
         run: |
-          aws lambda update-function-code --function-name ${{ matrix.lambdas }} --image-uri ${{ env.DOCKER_IMAGE_BASE }}${{ matrix.lambdas }}:${{ inputs.environment }}-${{ github.sha }} --publish
+          aws lambda update-function-code --function-name ${{ inputs.lambda_name }} --image-uri ${{ env.DOCKER_IMAGE_BASE }}${{ matrix.lambdas }}:${{ inputs.environment }} --publish
 
       # Send Slack notifying success
       - name: Slack Aselo channel
@@ -124,7 +105,7 @@ jobs:
         uses: slackapi/slack-github-action@v1.14.0
         with:
           channel-id: ${{ env.ASELO_DEPLOYS_CHANNEL_ID }}
-          slack-message: '`[HRM lambdas - ${{ matrix.lambdas }}]` Action ${{ github.workflow }} completed with SHA ${{ github.sha }} to region `${{ inputs.region }}`, environment `${{ inputs.environment }}` :rocket:.'
+          slack-message: '`[HRM lambdas - ${{ inputs.lambda_name }}]` Action ${{ github.workflow }} completed with SHA ${{ github.sha }} to region `${{ env.AWS_REGION }}`, environment `${{ inputs.environment }}` :rocket:.'
         env:
           SLACK_BOT_TOKEN: ${{ env.GITHUB_ACTIONS_SLACK_BOT_TOKEN }}
         if: ${{ inputs.send-slack-message != 'false' }}
