fix: set all regions to us-east-1 for now

diff --git a/.github/workflows/hrm-lambda-release.yml b/.github/workflows/hrm-lambda-release.yml
--- a/.github/workflows/hrm-lambda-release.yml
+++ b/.github/workflows/hrm-lambda-release.yml
@@ -66,7 +66,7 @@ jobs:
           echo ENVIRONMENT=$ENVIRONMENT >> $GITHUB_ENV
           echo LAMBDA_NAME=$LAMBDA_NAME >> $GITHUB_ENV
 
-          case "$ENVIRONMENT" in development) region="us-east-1" ;; staging) region="eu-west-1" ;; production) region="eu-west-1" ;; *) echo "Invalid environment: ${{ inputs.environment }}" && exit 1 ;; esac
+          case "$ENVIRONMENT" in development) region="us-east-1" ;; staging) region="us-east-1" ;; production) region="us-east-1" ;; *) echo "Invalid environment: ${{ inputs.environment }}" && exit 1 ;; esac
           echo AWS_REGION=$region >> $GITHUB_ENV
           echo AWS_DEFAULT_REGION=$region >> $GITHUB_ENV
           echo DOCKER_IMAGE_BASE=712893914485.dkr.ecr.${region}.amazonaws.com/${ENVIRONMENT}/hrm-lambdas- >> $GITHUB_ENV
