fix: bugs in env generation

diff --git a/.github/workflows/hrm-lambda-release.yml b/.github/workflows/hrm-lambda-release.yml
--- a/.github/workflows/hrm-lambda-release.yml
+++ b/.github/workflows/hrm-lambda-release.yml
@@ -84,10 +84,10 @@ jobs:
       - name: Set Env Based on Environment
 
         run: |
-          case "${{ inputs.environment }}" in development) region="eu-west-1" ;; staging) region="eu-west-1" ;; production) region="eu-west-1" ;; *) echo "Invalid environment: ${{ inputs.environment }}" && exit 1 ;; esac &&
-          echo AWS_REGION=$region >> $GITHUB_ENV &&
-          echo AWS_DEFAULT_REGION=$region >> $GITHUB_ENV &&
-          DOCKER_IMAGE_BASE=712893914485.dkr.ecr.${region}.amazonaws.com/${{ inputs.environment }}/hrm-lambdas-
+          case "${{ inputs.environment }}" in development) region="eu-west-1" ;; staging) region="eu-west-1" ;; production) region="eu-west-1" ;; *) echo "Invalid environment: ${{ inputs.environment }}" && exit 1 ;; esac
+          echo AWS_REGION=$region >> $GITHUB_ENV
+          echo AWS_DEFAULT_REGION=$region >> $GITHUB_ENV
+          echo DOCKER_IMAGE_BASE=712893914485.dkr.ecr.${region}.amazonaws.com/${{ inputs.environment }}/hrm-lambdas- >> $GITHUB_ENV
 
       - name: Compile Lambda
         run: |
